############################################
## containerfiles/buildargs/Containerfile ##
############################################

# The github workflow should completely overwrite this file.

ARG GIT_BRANCH='localhost'
ARG IMAGE_TAG='local'
ARG GIT_REPO="https://github.com/dkolb/bazzite-dkub"
ARG GIT_SHA='local-build'