name: bazzite-dkub
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - vscode.repo
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
    install:
      - code
      - hardinfo2
      - firefox
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.github.mtkennerly.ludusavi
        - io.podman_desktop.PodmanDesktop
      remove:
        - org.mozilla.firefox
  - type: bling
    install:
      - 1password
  - type: justfiles
    include:
      - enable-daily-ludsavi-backups.just
  - type: signing

