name: bazzite-dkub
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bazzite
image-version: stable
modules:
  - type: containerfile
    containerfiles:
      - buildargs
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - vscode.repo
      - google-chrome.repo
      - hardware_razer.repo
    keys:
      - https://packages.microsoft.com/keys/microsoft.asc
      - https://dl.google.com/linux/linux_signing_key.pub 
      - https://download.opensuse.org/repositories/hardware:/razer/Fedora_41/repodata/repomd.xml.key
    install:
      - code
      - hardinfo2
      - firefox
      - google-chrome-stable
      - kvantum
      - lact
      - openrazer-meta
      - razergenie
      - sddm-themes
  - type: default-flatpaks
    notify: true
    system:
      install:
        - com.github.mtkennerly.ludusavi
        - io.podman_desktop.PodmanDesktop
      remove:
        - org.mozilla.firefox
  - type: bling
    install:
      - 1password
  - type: justfiles
    include:
      - enable-daily-ludsavi-backups.just
      - luks-fido2.just
  - type: containerfile
    containerfiles:
      - labels
  - type: signing
