#!/usr/bin/bash

set -oue pipefail

IMAGE_INFO="/usr/share/ublue-os/image-info.json"
BAZZITE_IMAGE_INFO="/usr/share/ublue-os/bazzite-image-info.json"

FEDORA_VERSION=`jq -r '."fedora-version"' < $BAZZITE_IMAGE_INFO`  
BASE_IMAGE_VERSION=`jq -r '.version' < $BAZZITE_IMAGE_INFO`
VERSION="$FEDORA_VERSION.$(date '+%Y%m%d')"

IMAGE_BRANCH_NORMALIZED="$GIT_BRANCH"
IMAGE_PRETTY_NAME="Bazzite (DKub Edition) $VERSION"
IMAGE_LIKE="fedora"
HOME_URL="https://github.com/dkolb/bazzite-dkub"
DOCUMENTATION_URL="https://github.com/dkolb/bazzite-dkub"
SUPPORT_URL="https://github.com/dkolb/bazzite-dkub/issues"
BUG_SUPPORT_URL="https://github.com/ublue-os/bazzite/issues/"
LOGO_ICON="bazzite-logo-icon"
LOGO_COLOR="0;38;2;138;43;226"
CODE_NAME="Holographic"

IMAGE_REF="ostree-image-signed:docker://$IMAGE_REGISTRY/$IMAGE_NAME"

# IMAGE_TAG="" (should come from containerfile ARGs)
BASE_IMAGE_NAME="${BASE_IMAGE##*/}"
VERSION_PRETTY="$IMAGE_BRANCH_NORMALIZED ($VERSION)"


# Image Info File
cat > $IMAGE_INFO <<EOF
{
  "image-name": "$IMAGE_NAME",
  "image-flavor": "$GIT_BRANCH",
  "image-vendor": "$IMAGE_REGISTRY",
  "image-ref": "$IMAGE_REF",
  "image-tag": "$IMAGE_TAG",
  "image-branch": "$IMAGE_BRANCH_NORMALIZED",
  "git-sha": "$GIT_SHA",
  "git-repo": "$GIT_REPO",
  "base-image-name": "$BASE_IMAGE_NAME",
  "fedora-version": "$FEDORA_VERSION",
  "version": "${VERSION:-N/A}",
  "version-pretty": "${VERSION_PRETTY:-N/A}"
}
EOF

OS_RELEASE_PRETTY_NAME="Bazzite (DKub Edition) $VERSION (From ${BASE_IMAGE}:${BASE_IMAGE_VERSION})"

# OS Release File
sed -i "s/^VARIANT_ID=.*/VARIANT_ID=$IMAGE_NAME/" /usr/lib/os-release
sed -i "s|^PRETTY_NAME=.*|PRETTY_NAME=\"$OS_RELEASE_PRETTY_NAME\"|" /usr/lib/os-release
sed -i "s/^NAME=.*/NAME=\"$IMAGE_PRETTY_NAME\"/" /usr/lib/os-release
sed -i "s|^HOME_URL=.*|HOME_URL=\"$HOME_URL\"|" /usr/lib/os-release
sed -i "s|^DOCUMENTATION_URL=.*|DOCUMENTATION_URL=\"$DOCUMENTATION_URL\"|" /usr/lib/os-release
sed -i "s|^SUPPORT_URL=.*|SUPPORT_URL=\"$SUPPORT_URL\"|" /usr/lib/os-release
sed -i "s|^BUG_REPORT_URL=.*|BUG_REPORT_URL=\"$BUG_SUPPORT_URL\"|" /usr/lib/os-release
sed -i "s|^CPE_NAME=\"cpe:/o:fedoraproject:fedora|CPE_NAME=\"cpe:/o:universal-blue:${IMAGE_PRETTY_NAME,}|" /usr/lib/os-release
sed -i "s/^DEFAULT_HOSTNAME=.*/DEFAULT_HOSTNAME=\"${IMAGE_PRETTY_NAME,}\"/" /usr/lib/os-release
sed -i "s/^ID=fedora/ID=${IMAGE_PRETTY_NAME,}\nID_LIKE=\"${IMAGE_LIKE}\"/" /usr/lib/os-release
sed -i "s/^LOGO=.*/LOGO=$LOGO_ICON/" /usr/lib/os-release
sed -i "s/^ANSI_COLOR=.*/ANSI_COLOR=\"$LOGO_COLOR\"/" /usr/lib/os-release
sed -i "/^REDHAT_BUGZILLA_PRODUCT=/d; /^REDHAT_BUGZILLA_PRODUCT_VERSION=/d; /^REDHAT_SUPPORT_PRODUCT=/d; /^REDHAT_SUPPORT_PRODUCT_VERSION=/d" /usr/lib/os-release
sed -i "s|^VERSION_CODENAME=.*|VERSION_CODENAME=\"$CODE_NAME\"|" /usr/lib/os-release
sed -i "s|^BUILD_ID=.*|BUILD_ID=\"$VERSION_PRETTY\"|" /usr/lib/os-release
sed -i "s|^BOOTLOADER_NAME=.*|BOOTLOADER_NAME=\"$OS_RELEASE_PRETTY_NAME\"|" /usr/lib/os-release

# Fix issues caused by ID no longer being fedora
sed -i "s/^EFIDIR=.*/EFIDIR=\"fedora\"/" /usr/sbin/grub2-switch-to-blscfg