############################################
## containerfiles/postbuild/Containerfile ##
############################################

# Customize OS build info and update GRUB menu entries.
RUN \
  mv /usr/share/ublue-os/image-info.json /usr/share/ublue-os/bazzite-image-info.json && \
  /usr/libexec/containerbuild/image-info && \
  KERNEL_FLAVOR=bazzite /usr/libexec/containerbuild/build-initramfs && \
  ostree container commit
