name: bluebuild
on:
  schedule:
    - cron: "00 12 * * 2" # build at 12:00 UTC every Tuesday 
  push:
    branches:
      - main
    paths-ignore: # don't rebuild if only documentation has changed
      - "**.md"
  pull_request:
  workflow_dispatch: # allow manually triggering builds
jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false # stop GH from cancelling all matrix builds if one fails
      matrix:
        recipe:
          # !! Add your recipes here 
          - recipe.yml
    steps:
      - uses: actions/checkout@v4
       # the build is fully handled by the reusable github action
      - name: Determine IMAGE_TAG name
        id: image-tag-name
        env:
          EVENT_NAME: ${{ github.event_name }}
          BRANCH: ${{ github.ref_name }}
          PR_NUMBER: ${{ github.event.number }}
        run: |
          if [ "$EVENT_NAME" = "pull_request" ]; then
            echo "image-tag=pr${PR_NUMBER}" >> $GITHUB_OUTPUT
          else
            echo "image-tag=${BRANCH_NAME}" >> $GITHUB_OUTPUT
          fi
      - name: Build Image Info ARGS Containerfile
        working-directory: ./containerfiles/buildargs/
        shell: bash
        run: |
          printf "###\n# containerfiles/buildargs/Containerfile\n###\n\n" > Containerfile
          echo "ARG GIT_BRANCH='${{ github.ref_name }}'" >> Containerfile
          echo "ARG IMAGE_TAG='${{ inputs.image-tag }}'" >> Containerfile
          echo "ARG GIT_REPO='${{ github.server_url }}/${{ github.repository }}'" >> Containerfile
          echo "ARG GIT_SHA='${{ github.sha }}'" >> Containerfile
          printf "###\nend file\n###\n\n"
      - name: Build Image Lables Containerfile
        working-directory: ./containerfiles/labels
        shell: bash
        run: |
          printf "###\n# containerfiles/buildargs/Containerfile\n###\n\n" > Containerfile
          echo "LABEL org.opencontainers.image.version \"41.`date '+%Y%m%d'`\"" >> Containerfile
          echo "LABEL org.opencontainers.image.created \"`date -u +%Y-%m-%dT%H:%M:%SZ`\"" >> Containerfile
          echo "LABEL org.opencontainers.image.url \"${{ github.server_url }}/${{ github.repository }}\"" >> Containerfile
      - name: Build Custom Image
        uses: blue-build/github-action@v1.8
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
          skip_checkout: true
          build_opts: "--compression-format zstd"
          rechunk: true
