name: Bluebuild (PR)
on:
  pull_request:
jobs:
  build-image:
    permissions:
      contents: read
      packages: write
      id-token: write
    uses: ./.github/workflows/build.yml
    with:
      image-tag: "pr${{ github.event.number }}"
      recipes: '["pr_build.yml"]'
      event_number: ${{ github.event.number }}
    secrets: inherit
